spring.application.name=feedback-analytics

spring.datasource.url=jdbc:postgresql://localhost:5432/feedback_db
spring.datasource.username= postgres
spring.datasource.password= postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update


